;
; Efesto - Excel Formula Extractor System and Topological Ordering algorithm.
; Copyright (C) 2017 Massimo Caliman mcaliman@gmail.com
;
; This program is free software: you can redistribute it and/or modify
; it under the terms of the GNU Affero General Public License as published
; by the Free Software Foundation, either version 3 of the License, or
; (at your option) any later version.
;
; This program is distributed in the hope that it will be useful,
; but WITHOUT ANY WARRANTY; without even the implied warranty of
; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
; GNU Affero General Public License for more details.
;
; You should have received a copy of the GNU Affero General Public License
; along with this program.  If not, see <https://www.gnu.org/licenses/>.
;
; If AGPL Version 3.0 terms are incompatible with your use of
; Efesto, alternative license terms are available from Massimo Caliman
; please direct inquiries about Efesto licensing to mcaliman@gmail.com
;

; This file was generated by EFESTO v.2.0
;
; Text file: test/01-horizontal-range-index.clj
; Excel File: test/01-horizontal-range-index.xlsx
; Excel Formulas Number: 1
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; B1 = 0.0
; C1 = 1.0
; D1 = 2.0
; E1 = 3.0
; F1 = 4.0
; G1 = 5.0
; H1 = 6.0
; HORIZONTAL_RANGE!B5 = INDEX(B1:H1,3)
; A7 = 
; END-RAW-TEXT
B1:H1

=

[0.0 1.0 2.0 3.0 4.0 5.0 6.0]

B5

=

INDEX

(B1:H1, 3)
