;
; Efesto - Excel Formula Extractor System and Topological Ordering algorithm.
; Copyright (C) 2017 Massimo Caliman mcaliman@gmail.com
;
; This program is free software: you can redistribute it and/or modify
; it under the terms of the GNU Affero General Public License as published
; by the Free Software Foundation, either version 3 of the License, or
; (at your option) any later version.
;
; This program is distributed in the hope that it will be useful,
; but WITHOUT ANY WARRANTY; without even the implied warranty of
; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
; GNU Affero General Public License for more details.
;
; You should have received a copy of the GNU Affero General Public License
; along with this program.  If not, see <https://www.gnu.org/licenses/>.
;
; If AGPL Version 3.0 terms are incompatible with your use of
; Efesto, alternative license terms are available from Massimo Caliman
; please direct inquiries about Efesto licensing to mcaliman@gmail.com
;

; This file was generated by EFESTO v.2.0
;
; Text file: test/03-range-index.clj
; Excel File: test/03-range-index.xlsx
; Excel Formulas Number: 1
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; A1 = 1.1
; B1 = 1.2
; C1 = 
; D1 = 
; E1 = 
; F1 = 
; G1 = 
; A2 = 2.1
; B2 = 2.2
; A3 = 3.1
; B3 = 3.2
; A4 = 4.1
; B4 = 4.2
; A5 = 5.1
; B5 = 5.2
; A6 = 6.1
; B6 = 6.2
; A7 = 
; RANGE!A10 = INDEX(A1:B6,2,2)
; END-RAW-TEXT
A1:B6

=

[[1.1 1.2] [2.1 2.2] [3.1 3.2] [4.1 4.2] [5.1 5.2] [6.1 6.2]]

A10

=

INDEX

(A1:B6, 2, 2)
