;
; Efesto - Excel Formula Extractor System and Topological Ordering algorithm.
; Copyright (C) 2017 Massimo Caliman mcaliman@gmail.com
;
; This program is free software: you can redistribute it and/or modify
; it under the terms of the GNU Affero General Public License as published
; by the Free Software Foundation, either version 3 of the License, or
; (at your option) any later version.
;
; This program is distributed in the hope that it will be useful,
; but WITHOUT ANY WARRANTY; without even the implied warranty of
; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
; GNU Affero General Public License for more details.
;
; You should have received a copy of the GNU Affero General Public License
; along with this program.  If not, see <https://www.gnu.org/licenses/>.
;
; If AGPL Version 3.0 terms are incompatible with your use of
; Efesto, alternative license terms are available from Massimo Caliman
; please direct inquiries about Efesto licensing to mcaliman@gmail.com
;

; This file was generated by EFESTO v.2.0
;
; Text file: test/16-example-range-1.clj
; Excel File: test/16-example-range-1.xlsx
; Excel Formulas Number: 1
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; D3 = 0.0
; E3 = 1.0
; F3 = 2.0
; G3 = 3.0
; H3 = 4.0
; Foglio1!D7 = INDEX(D3:H3,2)
; END-RAW-TEXT
(def D3:H3 [0.0 1.0 2.0 3.0 4.0])
(def D7 (index D3:H3 2))
