;
; Efesto - Excel Formula Extractor System and Topological Ordering algorithm.
; Copyright (C) 2017 Massimo Caliman mcaliman@gmail.com
;
; This program is free software: you can redistribute it and/or modify
; it under the terms of the GNU Affero General Public License as published
; by the Free Software Foundation, either version 3 of the License, or
; (at your option) any later version.
;
; This program is distributed in the hope that it will be useful,
; but WITHOUT ANY WARRANTY; without even the implied warranty of
; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
; GNU Affero General Public License for more details.
;
; You should have received a copy of the GNU Affero General Public License
; along with this program.  If not, see <https://www.gnu.org/licenses/>.
;
; If AGPL Version 3.0 terms are incompatible with your use of
; Efesto, alternative license terms are available from Massimo Caliman
; please direct inquiries about Efesto licensing to mcaliman@gmail.com
;

; This file was generated by EFESTO v.2.0
;
; Text file: test/902-terminals-formulas.clj
; Excel File: test/902-terminals-formulas.xlsx
; Excel Formulas Number: 4
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; A1 = TRUE
; A2 = 1.838226
; A3 = 24.0
; A4 = This is a string
; Foglio1!A5 = 1/0
; Foglio1!A7 = IF(A1,A2,A3)
; Foglio1!A8 = IF(A1,A4,A7)
; Foglio1!A9 = IF(A1,A5,A3)
; END-RAW-TEXT
A1

=

TRUE

A5

=

"1/0"

A3

=

24.0

A4

=

"This is a string"

A2

=

1.838226

A9

=

IF

(A1, A5, A3)

A7

=

IF

(A1, A2, A3)

A8

=

IF

(A1, A4, A7)
