;
; Efesto - Excel Formula Extractor System and Topological Ordering algorithm.
; Copyright (C) 2017 Massimo Caliman mcaliman@gmail.com
;
; This program is free software: you can redistribute it and/or modify
; it under the terms of the GNU Affero General Public License as published
; by the Free Software Foundation, either version 3 of the License, or
; (at your option) any later version.
;
; This program is distributed in the hope that it will be useful,
; but WITHOUT ANY WARRANTY; without even the implied warranty of
; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
; GNU Affero General Public License for more details.
;
; You should have received a copy of the GNU Affero General Public License
; along with this program.  If not, see <https://www.gnu.org/licenses/>.
;
; If AGPL Version 3.0 terms are incompatible with your use of
; Efesto, alternative license terms are available from Massimo Caliman
; please direct inquiries about Efesto licensing to mcaliman@gmail.com
;

; This file was generated by EFESTO v.2.0
;
; Text file: test/903-terminals-formulas.clj
; Excel File: test/903-terminals-formulas.xlsx
; Excel Formulas Number: 2
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; A1 = TRUE
; A2 = 1.838226
; A3 = 24.0
; A4 = This is a string
; Foglio1!A6 = IF(A1,A2,A3)
; Foglio1!A7 = IF(A1,A4,A3)
; END-RAW-TEXT
(def A1 Boolean/TRUE)
(def A2 1.838226)
(def A3 24.0)
(def A4 "This is a string")
(def A6 (if A1 A2 A3))
(def A7 (if A1 A4 A3))
