;
; Efesto - Excel Formula Extractor System and Topological Ordering algorithm.
; Copyright (C) 2017 Massimo Caliman mcaliman@gmail.com
;
; This program is free software: you can redistribute it and/or modify
; it under the terms of the GNU Affero General Public License as published
; by the Free Software Foundation, either version 3 of the License, or
; (at your option) any later version.
;
; This program is distributed in the hope that it will be useful,
; but WITHOUT ANY WARRANTY; without even the implied warranty of
; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
; GNU Affero General Public License for more details.
;
; You should have received a copy of the GNU Affero General Public License
; along with this program.  If not, see <https://www.gnu.org/licenses/>.
;
; If AGPL Version 3.0 terms are incompatible with your use of
; Efesto, alternative license terms are available from Massimo Caliman
; please direct inquiries about Efesto licensing to mcaliman@gmail.com
;

; This file was generated by EFESTO v.2.0
;
; Text file: test/904-terminals-formulas.clj
; Excel File: test/904-terminals-formulas.xlsx
; Excel Formulas Number: 6
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; A1 = 10.0
; B1 = A1
; A2 = 20.0
; B2 = A2
; Foglio1!A3 = A1+A2
; B3 = A1+A2
; Foglio1!A4 = A1-A2
; B4 = A1-A2
; Foglio1!A5 = A1*A2
; B5 = A1*A2
; Foglio1!A6 = A1/A2
; B6 = A1/A2
; Foglio1!A7 = A1&A2
; B7 = A1&A2
; Foglio1!A8 = A1^A2
; B8 = A1^A2
; END-RAW-TEXT
A2

=

20.0

A1

=

10.0

A4

=

(A1-A2)

A5

=

(A1*A2)

A6

=

(A1/A2)

A3

=

(A1+A2)

A8

=

(A1 ^A2)

A7

=

(A1&A2)
